setup project configuration
pelan23/cypress-training pull request #1
Opened 2023-03-13 20:01 UTC by pelan23

Configuración inicial proyecto

2023-03-15 15:36 UTC, JuanDelahozMiranda requested changes

2023-03-15 15:36 UTC, JuanDelahozMiranda commented on .gitignore
Please fix the EOF.

2023-03-15 15:36 UTC, JuanDelahozMiranda commented on .github/CODEOWNERS
> +@holgiosalos @valeryibarra @aperdomob @manuelq12 @JuanDelahozMiranda
Please fix the EOF.

2023-03-22 16:45 UTC, pelan23 commented on .github/CODEOWNERS
> +@holgiosalos @valeryibarra @aperdomob @manuelq12 @JuanDelahozMiranda
EOF issue solved

2023-03-22 18:58 UTC, JuanDelahozMiranda approved these changes

2023-03-23 15:41 UTC, merged