setup cypress configuration
pelan23/cypress-training pull request #2
Opened 2023-03-23 15:59 UTC by pelan23

Installation and configuration of Cypress

2023-03-23 16:50 UTC, JuanDelahozMiranda requested changes

2023-03-23 16:50 UTC, JuanDelahozMiranda commented on cypress/support/commands.js
> +// Cypress.Commands.overwrite('visit', (originalFn, url, options) => { ... })
Fix EOF (append a blank line)

2023-03-23 16:50 UTC, JuanDelahozMiranda commented on cypress/support/e2e.js
> +// require('./commands')
Fix EOF (append a blank line)

2023-03-23 20:11 UTC, pelan23 commented on cypress/support/commands.js
> +// Cypress.Commands.overwrite('visit', (originalFn, url, options) => { ... })
fixed

2023-03-23 20:11 UTC, pelan23 commented on cypress/support/e2e.js
> +// require('./commands')
Fixed

2023-03-24 16:17 UTC, JuanDelahozMiranda approved these changes

2023-03-24 19:36 UTC, merged